### ISSUE TITLE
能否提供导出到本地 csv 文件功能

### ISSUE THREAD

**Issue by chinyajie** [Tit1e/kindle2Flomo#2]
微信笔记的获取和展示做的非常非常棒，能否提供直接导出到本地 csv 文件功能，这会使更多人收益。

**Comment by Tit1e** [comment]
好的，下个版本我会尝试加上这个功能，不过可能需要等待一段时间。

**Comment by Tit1e** [comment]
已支持单本图书 CSV 文件的导出，请更新软件版本

**Comment by chinyajie** [comment]
太棒了。🌺
