### ISSUE TITLE
提两个需求，望考虑🙏🏻

### ISSUE THREAD

**Issue by icepandamichael** [Tit1e/kindle2Flomo#3]
1. 导入Apple Books笔记时，能不能按照图书章节顺序排列。
2.导入一次之后能不能加个时间戳（或者其他解决方案），可以在下次导入同一本书的笔记时，能够快速定位到增量笔记。🙏🏻

**Comment by Tit1e** [comment]
第一个需求我已经处理，你可以在软件右上角检查更新进行自动更新，或者在 [releases](https://github.com/Tit1e/kindle2Flomo/releases) 中下载最新版本。
至于第二个需求，我会酌情考虑。
