### ISSUE TITLE
期望能支持Koreader中导出的标注 导入到Flomo

### ISSUE THREAD

**Issue by elain** [Tit1e/kindle2Flomo#4]
提个小需求，我平时使用Koreader，导出的html和txt有可能使用kindle2Flomo导入至flomo吗？不胜感激

**Comment by Tit1e** [comment]
已支持 KOReader JSON 格式笔记的导入 [v2.5.2](https://github.com/Tit1e/kindle2Flomo/releases/tag/v2.5.2)
网页端已同步更新
